spring:
  application:
    name: boot
  datasource:
    username: root
    password: qgy@cs741qgy
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.15.196.199:6533/SaaS?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: localhost
  header: X-JWT

server:
  port: 8080

sms:
  send: true

logging:
  level:
    root: INFO
    com.abuqool: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
  file: logs/server.log



